#!/usr/bin/lua

local site = require 'gluon.site_config'
local users = require 'gluon.users'
local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()
local lutil = require 'luci.util'

local update_enabled = uci.get('autoupdater','settings','enabled')

if (tonumber(update_enabled) == 1) then
  uci:set('autoupdater','settings','branch','l2tp-exp')
  uci:save('autoupdater')
  uci:commit('autoupdater')
end
os.remove('/lib/gluon/upgrade/901-switch2-l2tp-exp')
