#!/usr/bin/lua                                                                                                                                                           
                                                                                                                                                                         
local site = require 'gluon.site_config'                                                                                                                                 
local users = require 'gluon.users'                                                                                                                                      
local util = require 'gluon.util'                                                                                                                                        
                                                                                                                                                                         
local uci = require('luci.model.uci').cursor()                                                                                                                           
                                                                                                                                                                         
uci:delete('network','mesh_radio0_vlan')                                                                                                                                 
uci:delete('network','mesh_radio1_vlan')                                                                                                                                 
uci:save('network')                                                                                                                                                      
uci:commit('network')                                                                                                                                                    
-- os.remove('/lib/gluon/upgrade/901-cleanupmesh')                                                                                                                       

